### ISSUE TITLE
Add Progress Bar After TacO Prompt

### ISSUE THREAD

**Issue by ElvenChaos** [solacelost/update-arcdps#5]
After the prompt asking if arcdps can manage TacO, there is no indicator that the script is processing, and given the length of time spent processing during this phase users may think the script froze or failed.

**Comment by solacelost** [comment]
I will fix this and roll it into the next release, but not release just for this.

**Comment by solacelost** [comment]
@ElvenChaos I added some more textual output because I don't have a great way of detecting status at the places I think you were getting hung up.

Could you let me know if the latest update provides you the feedback you were hoping for? I can't think of anything else that could be hanging it up except the things I have now fixed.
